modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="fine_tuned_weaponry"
version="2.0.0"
displayName="Finetuned Weaponry"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="no credits yet"
authors="NAIZO"
description="This mod offers ALOT of new weapons with unique abilities"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fine_tuned_weaponry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.fine_tuned_weaponry]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration