modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="fine_tuned_weaponry"
version="1.1.0"
displayName="Fine-Tuned Weaponry"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="no credits yet"
authors="NAIZO"
description="This mod offers ALOT of new weapons with unique abilities"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fine_tuned_weaponry]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fine_tuned_weaponry]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration